ex:
	gcc -o server server.c -lpthread
	gcc -o client1 client1.c
	gcc -o client2 client2.c
	gcc -o client3 client3.c
	gcc -o multiply multiply.c
	gcc -o addition addition.c
	gcc -o subtract subtract.c
	make script
	rm -rf cli_*
	unlink server_fifo

